name = "FormalQualBench"
version = "1.0.0"
keywords = ["math", "benchmark"]
defaultTargets = ["FormalQualBench"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.28.0"

[[lean_lib]]
name = "FormalQualBench"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
